db_creds:
  drivername: postgres
  host: '<your_host_name>'
  port: '<your_port>'
  username: '<your_username>'
  password: '<your_password>'
  database: '<your_database_name>'

tables:
  - name: "your_table_name1"
    expectations:
      - name: "expect_column_to_exist"
        args: ["your_column_name"]
        kwargs: {}
      - name: "expect_column_values_to_not_be_null"
        args: ["your_column_name"]
        kwargs: {}
      - name: "expect_column_values_to_be_unique"
        args: ["your_column_name"]
        kwargs: {}
      - name: "expect_column_mean_to_be_between"
        args: ["your_column_name"]
        kwargs: {"min_value": 0, "max_value": 100}
  - name: "your_table_name2"
    expectations:
      - name: "expect_column_to_exist"
        args: ["your_column_name"]
        kwargs: {}
      - name: "expect_column_values_to_not_be_null"
        args: ["your_column_name"]
        kwargs: {}
      - name: "expect_column_values_to_be_unique"
        args: ["your_column_name"]
        kwargs: {}
      - name: "expect_column_mean_to_be_between"
        args: ["your_column_name"]
        kwargs: {"min_value": 0, "max_value": 100}
