db_creds:
  drivername: postgres
  host: 'localhost'
  port: '5432'
  username: 'postgres'
  password: 'notapassword'
  database: 'Adventureworks'
  schema: 'production'

tables:
  - name: "productinventory"
    expectations:
      - name: "expect_column_to_exist"
        args: ["location_id"]
        kwargs: {}
      - name: "expect_column_values_to_not_be_null"
        args: ["bin"]
        kwargs: {}
      - name: "expect_column_values_to_be_unique"
        args: ["rowguid"]
        kwargs: {}
