expectation_suite_name: "default_suite"
meta:
  great_expectations_version: "0.16.0"
  version: "1.0.0"
expectations:
- expectation_type: expect_table_row_count_to_be_between
  kwargs:
    min_value: 100
    max_value: 1000
- expectation_type: expect_column_values_to_not_be_null
  kwargs:
    column: "column_name" # Replace with your column name
- expectation_type: expect_column_values_to_be_in_set
  kwargs:
    column: "another_column_name" # Replace with your column name
    value_set: [ "value1", "value2", "value3" ] # Provide valid values for your column